---
- name: Start Dashy
  block:
    - name: Create Dashy Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dashy_data_directory }}"

    - name: Copy base config
      ansible.builtin.copy:
        src: conf.yml
        dest: "{{ dashy_data_directory }}/conf.yml"
        force: no

    - name: Dashy Docker Container
      community.docker.docker_container:
        name: "{{ dashy_container_name }}"
        image: lissy93/dashy:latest
        pull: true
        ports:
          - "{{ dashy_port }}:8080"
        restart_policy: unless-stopped
        memory: "{{ dashy_memory }}"
        volumes:
          - "{{ dashy_data_directory }}:/app/user-data:rw"
        env:
          NODE_ENV: "production"
          IS_DOCKER: "true"
        labels:
          traefik.enable: "{{ dashy_available_externally | string }}"
          traefik.http.routers.dashy.rule: "Host(`{{ dashy_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.dashy.entrypoints: "web"
          traefik.http.services.dashy.loadbalancer.server.port: "8080"
  when: dashy_enabled is true

- name: Stop Dashy
  block:
    - name: Stop Dashy
      community.docker.docker_container:
        name: "{{ dashy_container_name }}"
        state: absent
  when: dashy_enabled is false
