[tls]
  [[tls.certificates]]
    certFile = "/certs/cert.pem"
    keyFile = "/certs/key.pem"

[http]
  [http.routers]
    [http.routers.homepage]
      rule = "Host(`home.1815.space`)"
      service = "homepage"
      tls = {}

    [http.routers.traefik-dashboard]
      rule = "Host(`traefik.1815.space`)"
      service = "api@internal"
      tls = {}

  [http.services]
    [http.services.homepage]
      [http.services.homepage.loadBalancer]
        [[http.services.homepage.loadBalancer.servers]]
          url = "http://192.168.12.210:11111"