---
- name: Create rTorrent Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_nas_user }}"
    group: "{{ ansible_nas_user }}"
    mode: '0755'
  with_items:
    - "{{ rtorrent_data_directory }}"
    - "{{ rtorrent_data_directory }}/config"
    - "{{ rtorrent_data_directory }}/rutorrent"
    - "{{ rtorrent_download_directory }}"
  tags: rtorrent

- name: Create rTorrent Docker Container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: "{{ rtorrent_container_name }}"
    image: "{{ rtorrent_image_name }}:{{ rtorrent_image_tag }}"
    pull: true
    state: "{{ 'started' if rtorrent_enabled else 'absent' }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ rtorrent_data_directory }}/config:/config:rw"
      - "{{ rtorrent_data_directory }}/rutorrent:/data:rw"
      - "{{ rtorrent_download_directory }}:/downloads:rw"
    ports:
      - "{{ rtorrent_port_http }}:8080"  # ruTorrent web UI
      - "{{ rtorrent_port_rt }}:6881"     # BitTorrent
      - "{{ rtorrent_port_rt }}:6881/udp" # BitTorrent UDP
      - "{{ rtorrent_port_dht }}:6881/udp" # DHT UDP
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ rtorrent_user_id }}"
      PGID: "{{ rtorrent_group_id }}"
      RU_REMOVE_CORE_PLUGINS: "erasedata"  # Remove unnecessary plugins (keeping httprpc for Radarr/Sonarr)
      RU_HTTP_USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    labels:
      traefik.enable: "{{ rtorrent_available_externally | string }}"
      traefik.http.routers.rtorrent.rule: "Host(`{{ rtorrent_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.rtorrent.entrypoints: "web"
      traefik.http.services.rtorrent.loadbalancer.server.port: "8080"
    memory: "{{ rtorrent_memory }}"
  tags: rtorrent

- name: Stop rTorrent
  block:
    - name: Stop rTorrent
      community.docker.docker_container:
        name: "{{ rtorrent_container_name }}"
        state: stopped
    - name: Remove rTorrent
      community.docker.docker_container:
        name: "{{ rtorrent_container_name }}"
        state: absent
  when: not rtorrent_enabled
  tags: rtorrent