---
- name: Start Stash
  block:
    - name: Create Stash Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ stash_data_directory }}"
        - "{{ stash_media_directory }}"
        - "{{ stash_metadata_directory }}"
        - "{{ stash_cache_directory }}"
        - "{{ stash_generated_directory }}"

    - name: Create Stash Docker Container
      community.docker.docker_container:
        name: "{{ stash_container_name }}"
        image: "{{ stash_image_name }}:{{ stash_image_version }}"
        pull: true
        volumes:
          - "{{ stash_data_directory }}:/root/.stash"
          - "{{ stash_media_directory }}:/data"
          - "{{ stash_metadata_directory }}:/metadata"
          - "{{ stash_cache_directory }}:/cache"
          - "{{ stash_generated_directory }}:/generated"
          - "/mnt/truenas-media:/mnt/truenas-media:rw"
        ports:
          - "{{ stash_port }}:9999"
        env:
          STASH_STASH: "/data"
          STASH_GENERATED: "/generated"
          STASH_METADATA: "/metadata"
          STASH_CACHE: "/cache"
          STASH_PORT: "9999"
          STASH_EXTERNAL_HOST: "https://{{ stash_hostname }}.{{ ansible_nas_domain }}"
          TZ: "{{ stash_timezone }}"
          PUID: "{{ stash_user_id }}"
          PGID: "{{ stash_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ stash_memory }}"
        labels:
          traefik.enable: "{{ stash_available_externally | string }}"
          traefik.http.routers.stash.rule: "Host(`{{ stash_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.stash.entrypoints: "web"
          traefik.http.services.stash.loadbalancer.server.port: "9999"
          traefik.http.middlewares.stash-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
          traefik.http.routers.stash.middlewares: "stash-headers"
  when: stash_enabled is true

- name: Stop Stash
  block:
    - name: Stop Stash
      community.docker.docker_container:
        name: "{{ stash_container_name }}"
        state: absent
  when: stash_enabled is false